# Generated by Django 5.0.5 on 2024-09-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(choices=[('ALMAGUER', 'Almaguer'), ('ARGELIA', 'Argelia'), ('BALBOA', 'Balboa'), ('BOLÍVAR', 'Bolívar'), ('BUENOS AIRES', 'Buenos Aires'), ('CAJIBIO', 'Cajibío'), ('CALDONO', 'Caldono'), ('CALOTO', 'Caloto'), ('CORINTO', 'Corinto'), ('EL TAMBO', 'El Tambo'), ('FLORENCIA', 'Florencia'), ('GUACHENÉ', 'Guachené'), ('GUAPI', 'Guapi'), ('INZA', 'Inza'), ('JAMBALO', 'Jambaló'), ('LA SIERRA', 'La Sierra'), ('LA VEGA', 'La Vega'), ('LÓPEZ DE MICAY', 'López'), ('MERCADERES', 'Mercaderes'), ('MIRANDA', 'Miranda'), ('MORALES', 'Morales'), ('PATIA (EL BORDO)', 'Patía (El Bordo)'), ('PAEZ (BELALCAZAR)', 'Páez (Belalcázar)'), ('PIENDAMÓ', 'Piendamó'), ('PIAMONTE', 'Piamonte'), ('POPAYÁN', 'Popayán'), ('ROSAS', 'Rosas'), ('PUERTO TEJADA', 'Puerto Tejada'), ('PURACÉ (COCONUCO)', 'Puracé (Coconuco)'), ('SAN SEBASTIÁN', 'San Sebastián'), ('SANTANDER DE QUILICHAO', 'Santander de Quilichao'), ('SANTA ROSA', 'Santa Rosa'), ('SILVIA', 'Silvia'), ('SOTARA (PAISPAMBA)', 'Sotará (Paispamba)'), ('SUCRE', 'Sucre'), ('SUAREZ', 'Suarez'), ('TIMBIO', 'Timbío'), ('TORIBIO', 'Toribio'), ('TIMBIQUI', 'Timbiquí'), ('TOTORO', 'Totoró'), ('VILLA RICA', 'Villa Rica')], max_length=150),
        ),
    ]
