# Generated by Django 5.0.5 on 2024-09-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_municipio_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programas_formacion',
            name='programa_formacion',
            field=models.CharField(choices=[('.ATENCION INTEGRAL A LA PRIMERA INFANCIA', '.ATENCION INTEGRAL A LA PRIMERA INFANCIA'), ('ABORDAJE DE PERSONAS CON DISCAPACIDAD', 'ABORDAJE DE PERSONAS CON DISCAPACIDAD')], max_length=150),
        ),
    ]
