# Generated by Django 5.0.5 on 2024-09-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p04',
            name='identificador_ficha',
            field=models.IntegerField(),
        ),
    ]
